# Generated by Django 4.0.4 on 2022-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='testcases',
            field=models.CharField(max_length=100),
        ),
    ]
