# Generated by Django 4.0.4 on 2022-04-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_problem_testcases'),
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittedAt', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.problem')),
            ],
        ),
    ]
