# Generated by Django 4.0.4 on 2022-04-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
