# Generated by Django 4.0.4 on 2022-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='testcases',
            new_name='test_input',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_output',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
