# Generated by Django 4.0.4 on 2022-05-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_submission_verdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_output',
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=500)),
                ('output', models.CharField(max_length=500)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.problem')),
            ],
        ),
    ]
